server:
  port: 8000
spring:
  application:
    name: qoo-takeaway
  datasource:
    druid:
      # 数据库
      url: jdbc:mysql://localhost:3306/takeout
      # 用户名
      username: root
      # 密码
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      filters: stat,wall

  redis:
    # redis 地址
    host: 127.0.0.1
    # 端口
    port: 6379
    timeout: 600
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
  servlet:
    multipart:
      max-request-size: 2MB
      max-file-size: 2MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_deleted
  type-aliases-package: com.easterfg.takeaway.domain

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

springfox:
  documentation:
    swagger-ui:
      # 是否启用swagger
      enabled: true

upload:
  # 文件上传路径
  path: /usr/takeaway/upload

jwt:
  # 密钥, 只能填写英文和数字
  secret: keys
  header: authorization
  expire: 288000
# 支付宝支付配置
alipay:
  # appID
  app-id:
  # 支付网关地址
  server-url:
  # 异步通知网址
  notify:
  # 公钥位置
  public-key: app_public_key.pem
  # 私钥位置
  private-key: app_private_key.pem
  charset: UTF-8
  sign-type: RSA2

# debug模式
debug: true
