server:
  port: 8000
spring:
  application:
    name: qoo-takeaway
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/takeout
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      filters: stat,wall
  #      stat-view-servlet:
  #        enabled: true
  #        url-pattern: /druid/*
  #        reset-enable: false
  #        login-username: druid
  #        login-password: druid
  #        allow: 127.0.0.1
  #      web-stat-filter:
  #        enabled: true
  #        url-pattern: /*
  #        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

  redis:
    timeout: 600
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
  servlet:
    multipart:
      max-request-size: 2MB
      max-file-size: 2MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_deleted
  type-aliases-package: com.easterfg.takeaway.domain

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

springfox:
  documentation:
    swagger-ui:
      # 是否启用swagger
      enabled: true

upload:
  # 文件上传路径
  path: 请填写文件上传路径

jwt:
  # 密钥
  secret: 填写jwt密钥
  header: authorization
  expire: 288000
# 支付宝支付配置
alipay:
  # appID
  app-id: 填写appid
  # 支付网关地址
  server-url: https://openapi.alipaydev.com/gateway.do
  # 异步通知网址
  notify: 填写异步通知地址
  # 公钥
  public-key: 填写公钥
  charset: UTF-8
  sign-type: RSA2
  private-key: 填写私钥路径
# debug模式
#debug: true
